#!/bin/bash
set -x 

derive_cluster_details_infra()
{
 path=$(pwd) 
 ## Get kubeconfig file into infra-setup gitlab runner pod
 mkdir $path/.kube-openebs
 mkdir ~/.kube
 cp  $path/.kube/config $path/.kube-openebs/config
 cp  $path/.kube/config ~/.kube/config
 cat $path/.kube/clusters > $path/.kube-openebs/clusters
}
 
setup_cluster_config_test()
{
 path=$(pwd)	
 mkdir ~/.kube
 cp $path/.kube-openebs/config ~/.kube/config
 mkdir ~/logs
 cp $path/.kube-openebs/clusters ~/logs
}

if [[ $1 == "infra-setup" ]]; then
 derive_cluster_details_infra;
elif [[ $1 == "litmus-test" ]]; then
 setup_cluster_config_test;
else echo "invalid job type"; exit 1
fi

