#!/bin/bash

set -e

echo $SDK_TOKEN > key.json
gcloud auth activate-service-account --key-file=key.json
gcloud config set project openebs-ci
export GOOGLE_APPLICATION_CREDENTIALS="/openebs/e2e-gcp/key.json"
echo "cleanup"
mkdir ~/logs
cp .kube/clusters ~/logs
cp .kube/vpc ~/logs
git clone https://github.com/openebs/litmus.git
cd litmus/k8s/gcp/k8s-installer/
echo "cleanup"
ansible-playbook delete-k8s-cluster.yml
ansible-playbook delete-vpc.yml --extra-vars "project=openebs-ci"
