#!/bin/bash
set -e
#########
#set-up EYE on client
mkdir .kube-openebs
mkdir ~/.kube
cp  .kube/config .kube-openebs/config
cp  .kube/config ~/.kube/config
cat /openebs/e2e-gcp/.kube/clusters > .kube-openebs/clusters

echo " deploying Aggrigrator and Forwarder on client"
wget https://raw.githubusercontent.com/openebs/e2e-infrastructure/master/production/efk-client/playbook/efk-vars.yml
wget https://raw.githubusercontent.com/openebs/e2e-infrastructure/master/production/efk-client/playbook/efk.yml
wget https://raw.githubusercontent.com/openebs/e2e-infrastructure/master/production/efk-client/playbook/get_url.yml
ansible-playbook efk.yml --extra-vars "commit_id=$CI_COMMIT_SHA pipeline_id=$CI_PIPELINE_IID"
##########

# Deploy OpenEBS

echo "deploying OpenEBS"

wget https://raw.githubusercontent.com/ashishranjan738/testlit/master/openebsinstaller0.6.yaml
kubectl apply -f openebsinstaller0.6.yaml
wget https://raw.githubusercontent.com/ashishranjan738/testlit/master/storageclass_setup.yaml
kubectl apply -f storageclass_setup.yaml
